#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
  whitelist_external_dirs: !secret homeassistant_whitelist

api:
frontend:
updater:
  reporting: no
  include_used_components: true
sun:
#ios:
map:
config:
discovery:
  ignore:
#    - sonos
    - netgear_router
    - harmony
    - google_cast
    - philips_hue
    - yeelight
#conversation:
logger: !include logger.yaml

logbook: !include logbook.yaml

http:
  # Using NGINX Reverse Proxy with SSL
  api_password: !secret ha_password
  trusted_proxies:
    - 192.168.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
  use_x_forwarded_for: True


#################################################################
## Components
#################################################################

google:
  client_id: !secret google_oauth_id
  client_secret: !secret google_oauth_secret
  track_new_calendar: false



emulated_hue:
#  type: alexa
  host_ip: !secret ha_host
  listen_port: 8300
  expose_by_default: false

ffmpeg:

hue:
  bridges:
    - host: !secret hue_hub_host

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: REDACTED
  username: !secret mqtt_user
  password: !secret mqtt_pass

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret



#ring:
 # username: !secret ring_username
  #password: !secret ring_password


#sonos:
 # media_player:
  #  hosts:
   #   - !secret sonos_chalkboard_host
    #  - !secret sonos_den_host
     # - !secret sonos_kitchen_host
      #- !secret sonos_office_host

tts:
  - platform: google
    cache: true
    time_memory: 300


#xiaomi_aqara:
 # discovery_retry: 5
  #gateways:
   # - key: !secret xiaomi_key

zwave:
  usb_path: /dev/ttyACM0
#  new_entity_ids: true
#  config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config
  polling_interval: 30000
  device_config:
    light.ge_14294_porch_level:
      polling_intensity: 1
      refresh_value: true
    light.ge_14294_exterior_side_level:
      polling_intensity: 1
      refresh_value: true

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
script: !include scripts.yaml
remote: !include remote.yaml
media_player: !include media_player.yaml
